### ISSUE TITLE
Does not work with Babel 6.0

### ISSUE THREAD

**Issue by Grmiade** [andreypopp/autobind-decorator#13]
I have not managed to run `autobind` decorator with babelify 7.2.0 and babel 6.0.15, the lasts versions.
I don't have errors but i think that `autobind` is not made, I have to make it for the hand.

My configuration in gulp:

```
...
transform: [babelify.configure({
      presets: ["react", "stage-0", "es2015"],
    })],
...
```

My bad ?

**Comment by ebello** [comment]
It looks like this is a [known issue](https://phabricator.babeljs.io/T2645) with Babel 6.0. Decorator support has been removed as the spec is changing rapidly.

**Comment by DanielMSchmidt** [comment]
Hi there,

you may use the [transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) plugin, this works fine with Babel 6.0.

**Comment by emirotin** [comment]
Doesn't work with react-hot-loader though.

It only defines getter while hot-loader tries to patch the property.
```
 function patchProperty(proto, key) {
    proto[key] = storedPrototype[key];
```

**Comment by andreypopp** [comment]
@emirotin try react-transform-hmr or react-hot-loader v2 (I think alpha is published on npm). v1 doesn't support getters.

**Comment by emirotin** [comment]
Thanks for the tip! I'm new to React ecosystem which is huge :)

**Comment by jhabdas** [comment]
No issues [using this with Babel 6](http://technologyadvice.github.io/es7-decorators-babel6/). Thank you so much for creating this stop gap library! This issue can be closed, or a new one opened if HMR continues to be an issue for some.

**Comment by anthonator** [comment]
@jhabdas do you mind sharing how you got it to work?

**Comment by stevemao** [comment]
98968ee should have fixed this. Please try the latest master branch :)

**Comment by jhabdas** [comment]
Cheers to you good friend. Cheers to you.
