### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by elijahdorman** [andreypopp/autobind-decorator#24]
The package.json file says MIT license, but no licence is included. The actual source says the copyright is personal without granting any rights to other users. It would be great if this could be straightened out.

``` javascript
/**
 * @copyright 2015, Andrey Popp <8mayday@gmail.com>
 *
```

**Comment by andreypopp** [comment]
Isn't including actual license test optional? I'd accept a pull request with license text if needed.

**Comment by elijahdorman** [comment]
I'm not a lawyer, but some clients I deal with have a very strong feeling on the subject (they don't want any possible risk). I can fork and make a PR if you'd like or the license can just be put in a LICENSE.txt file (or whatever).

https://opensource.org/licenses/MIT

**Comment by awesomeaniruddh** [comment]
If you wanna include a common license like MIT or Apache, you can click 'Create new file' on the code tab and type in LICENSE as the file name. Github will then show you an option to auto-fill the file contents with a license.

**Comment by kesha-antonov** [comment]
@andreypopp Hello! Any update on this?

What @awesomeaniruddh suggested is good solution 👍

**Comment by andreypopp** [comment]
@kesha-antonov 

>  I'd accept a pull request with license text if needed.

**Comment by kesha-antonov** [comment]
@andreypopp Yeah, sure! Missed that.

https://github.com/andreypopp/autobind-decorator/pull/45
