### ISSUE TITLE
Rationalle for autobind decorator comparing to = () => syntax sugar

### ISSUE THREAD

**Issue by playpauseandstop** [andreypopp/autobind-decorator#3]
In time of introducing React 0.13 Facebook devs ran into same problem and proposed to autobind method syntactically as:

```
class Counter extends React.Component {
  tick = () => {
    ...
  }
  ...
}
```

This syntax already work when using Babel with stage=0 setting, so I want to understand what problems solved ``@autobind`` decorator and is it ok, when one goal reached by two completely different ways?

More about autobinding [from React v0.13.0 Beta 1 blog post](http://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding)

**Comment by andreypopp** [comment]
So
```
class Counter extends React.Component {
  tick = () => {
    ...
  }
  ...
}
```
vs.
```
class Counter extends React.Component {
  @autobind
  tick() {
    ...
  }
  ...
}
```
Don't have the answer so just some observations.

Both are explicit about the intentions.

Instance property version props:
* Doesn't require using 3rd party code

Instance property version cons:
* Looks too cryptic
* It doesn't really clear from syntax what `this` does point to inside the function.

Decorator version pros:
* Looks like a method (but decorated)

Decorator version cons:
* Look too cryptic (though a little less cryptic to me than instance property version)

**Comment by dominataa** [comment]
One advantage of the decorator and bound method would be that when debugging you should get a named function vs an anonymous function. I guess that would just be down to personal preference of the developer or what syntax they prefer. The react solution is certainly simple.

**Comment by playpauseandstop** [comment]
Thanks for clarification, this should be closed now, after fixing https://github.com/babel/babel-eslint/issues/71 I prefer to stay on ``() => {}`` syntax, but would know that there is ``@autobind`` alternative.

**Comment by gaearon** [comment]
One pro is we'll be able to support hot reloading decorated version in React Hot Loader 2 (you can try `react-hot-loader@2.0.0-alpha`). We'll eventually get to supporting property syntax too, but probably outside React Hot Loader, with a Babel plugin, and not very soon. :-)

**Comment by seeden** [comment]
Hi guys, 
when you are using () => {} you are not able to override this method in extended class. This is the huge disadvantage.

@autobind is great but sometimes is better to use ES7 :: instead of bind
