### ISSUE TITLE
"Cannot set property" error on React class component method

### ISSUE THREAD

**Issue by AndrewRayCode** [andreypopp/autobind-decorator#32]
I'm guessing I'm missing something but not sure what.

My `.babelrc`:

``` javascript
{
  "presets": ["react", "es2015", "stage-0"],

  "plugins": [
    "transform-decorators-legacy"
  ],

  "env": {
    "development": {
      "plugins": [ "typecheck" ]
    }
  }
}
```

My webpack loader config:

``` javascript
{
    test: /\.jsx?$/,
    exclude: /node_modules/,
    loaders: [ 'react-hot', 'babel?presets[]=es2015&presets[]=react&presets[]=stage-0&plugins[]=transform-decorators-legacy' ]
}
```

My `.eslintrc` (I have no idea if both of these are needed):

``` javascript
  "parser": "babel-eslint",
  "settings": {
    "import/parser": "babel-eslint",
```

In my React component, I use the autobind decorator:

``` javascript
import autobind from 'autobind-decorator';

export default class Home extends Component {

    @autobind
    onPress() {}

}
```

But I get the runtime error:

> makeAssimilatePrototype.js:21 Uncaught TypeError: Cannot set property onPress of #<Home> which has only a getter

**Comment by InfernoZeus** [comment]
Just started getting this issue as well - no idea what's triggered the change. The only thing I did was extract a class into its own file, but I don't think that caused it.

**Comment by DelvarWorld** [comment]
@InfernoZeus what version of React are you using? Wondering if component classes changed something internally recently. Or maybe how Babel handles classes?

For me:
React 15.2.1
babel-core 6.11.4

**Comment by InfernoZeus** [comment]
I'm using the same version of React, and a slightly earlier version of babel-core: 6.10.4

**Comment by VinceFanZ** [comment]
I've had the same problem.

**Comment by VinceFanZ** [comment]
user import { autobind } from 'core-decorators'

**Comment by smashercosmo** [comment]
https://github.com/gaearon/react-transform-catch-errors/issues/26 probably related

**Comment by alexilyaev** [comment]
@VinceFanZ Did not work for me with `core-decorators`

**Comment by myknbani** [comment]
I'm not experiencing this bug.

autobind-decorator: 1.3.3
react: 15.3.1

but I use Browserify, I can't imagine how a bundler could break things though.

**Comment by Jinnified** [comment]
@smashercosmo if my dependency's dependency has react-transform-catch-errors and i have transform-decorators-legacy, could this still causing issues?

**Comment by alexilyaev** [comment]
This might be related:  
https://github.com/jayphelps/core-decorators.js/issues/48#issuecomment-200592851

**Comment by iamricky** [comment]
I'm still receiving the `Uncaught TypeError: Cannot set property render of #<ComponentName> which has only a getter` when binding to the class, e.g.

```
@autobind
class Component { }
```

Has this issue been addressed? Please advise.

source:
[https://github.com/gaearon/react-transform-catch-errors/issues/26#issuecomment-197078851](Doesn't work when used together with babel-plugin-transform-decorators-legacy)

**Comment by AndrewRayCode** [comment]
I think this project is abandonware that will only work with older versions of something (babel? react?)

**Comment by stevemao** [comment]
See https://github.com/andreypopp/autobind-decorator/pull/29

**Comment by farzer** [comment]
met the same problem, anything else solution?

**Comment by smashercosmo** [comment]
I fixed it long time ago in react-transform-catch-errors https://github.com/gaearon/react-transform-catch-errors/commit/afbbda89959e886e636d00427f20b6efc80bf441 It just wasn't published. Installing directly from master should work for everyone who faced this issue.

**Comment by stevemao** [comment]
98968ee should have fixed this. Please try the latest master branch :)

**Comment by alexilyaev** [comment]
With react-hot-loader 3 this worked with version v1.4.1 as well.  
Tested now with v2.1.0, still works.
