### ISSUE TITLE
@autobind decorator is not working in react-native 0.32

### ISSUE THREAD

**Issue by anuragalla** [andreypopp/autobind-decorator#33]
It gives the following error
![screen shot 2016-09-16 at 9 17 31 pm](https://cloud.githubusercontent.com/assets/9738350/18592716/d48e1df2-7c55-11e6-96b7-df86f9f26123.png)

**Comment by stevemao** [comment]
@anuragalla is it still happening with the latest versions?

**Comment by anuragalla** [comment]
Not anymore this should help you. 

````
npm install --save-dev babel-plugin-transform-decorators-legacy
````
.babelrc
````
{
	 "presets": [
	    "react-native"
	  ],
	  "plugins": ["transform-decorators-legacy"]
}
````

**Comment by stevemao** [comment]
Closing since this is not a problem with this module.
