### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by andreypopp** [andreypopp/autobind-decorator#35]
As I no longer use this library it needs new maintainers.

**Comment by stevemao** [comment]
Hi @andreypopp I'm really keen to maintain this. My company Atlassian is using this so I have good support.

**Comment by stevemao** [comment]
cc @bradleyayers

**Comment by andreypopp** [comment]
Nice, let's wait some time (a day) so others can respond too. Also cc @domarmstrong as he already has commit access to the repo.

**Comment by bradleyayers** [comment]
@andreypopp I'm interested why you no longer use this. Do you have a different pattern that you use now?

**Comment by andreypopp** [comment]
@bradleyayers completely switched to use class instance properties:
```
onClick = (e) => {
  ...
};
```

**Comment by stevemao** [comment]
typescript doesn't seem to support this yet.

**Comment by andreypopp** [comment]
@stevemao what's you npm username so I could add you there?

**Comment by domarmstrong** [comment]
Sounds good @stevemao! Sadly I don't use either for quite a while now as I moved in other directions now.

**Comment by stevemao** [comment]
Hi @andreypopp can you add @bradleyayers as well? Also would you mind adding me to npm? Thanks guys.

**Comment by stevemao** [comment]
If not, can you do a release now?

**Comment by stevemao** [comment]
> @stevemao what's you npm username so I could add you there?

Sorry, It's [stevemao](https://www.npmjs.com/~stevemao)

**Comment by andreypopp** [comment]
> Hi @andreypopp can you add @bradleyayers as well? Also would you mind adding me to npm?

Done

**Comment by mockdeep** [comment]
@andreypopp out of curiosity, how are you handling binding now?

**Comment by bradleyayers** [comment]
I just use the standard ES7 property assignment:

    foo = () => { ... }

**Comment by baba43** [comment]
@bradleyayers I found this to cause problems while hot reloading since methods created this way will not be hot loaded.

**Comment by nurbek-ab** [comment]
@baba43 Also class property methods cause problems with testing. For example you cannot use `jest.spyOn` on a class property method because it's not in the prototype.

**Comment by stevemao** [comment]
@nurbek-ab there's already tickets. Please search the issue tracker and find the solutions
