### ISSUE TITLE
`this.props` evaluates to `undefined` when using @autobind

### ISSUE THREAD

**Issue by aymericbouzy** [andreypopp/autobind-decorator#41]
I have a weird behaviour with about 300 Components rendered in a ListView where for some of them, I get an error because for some reason `this.props` is undefined in an auto binded method. If I use the usual syntax to bind my method in the constructor, the error goes away. I do not get the error in every Component, only some of them, in particular those at the end of the listView. All components are rendered the same way. I have the same behaviour when using my own autobind method inspired from `react-autobind`.

**Comment by wkh237** [comment]
Have the same problem, in my case,  it also happens even not using `autobind`, as a workaround manually bind context in constructor and  it solves the issue. 

```js
class foo extends Component {

  constructor(props) {
    super(props);
    this._bar = this._bar.bind(this);
  }

  _bar() {
    this.props.foobar();
  }

}
```

It'd be great to know why this is going to happen, thanks !

**Comment by robclouth** [comment]
I'm getting the same on RN 0.40, only on Android. In a ListView, but also with NavigatorExperimental. It seems that the Components are getting torn down and recreated but the autobind wrapper isn't.

**Comment by stevemao** [comment]
@aymericbouzy Can you create a minimal replication of the problem?

**Comment by aymericbouzy** [comment]
Well ... I'll give it a try, but I don't even recall which exact component it was ... Our code changes all the time ... Let's hope I find the bug again!

**Comment by aymericbouzy** [comment]
I can't reproduce anymore. Maybe migrating to a higher version of RN solved it. You can close for now, and I'll keep you posted if it happens again. Thanks anyway !

**Comment by lprhodes** [comment]
Seeing this too when using autobind on cells in a react native flat list (Android only)

**Comment by stevemao** [comment]
Maybe related to https://github.com/andreypopp/autobind-decorator/pull/57

**Comment by lprhodes** [comment]
Perfect thanks @stevemao!
