### ISSUE TITLE
I'm not able to use this autobind decorator this with TypeScript

### ISSUE THREAD

**Issue by rfgamaral** [andreypopp/autobind-decorator#43]
Just looked at #37 too, but neither this:

```ts
import autobind from 'autobind-decorator'
```

Nor this:

```ts
import * as autobind from 'autobind-decorator'
```

Works for me... The first complains about a missing default export, the second gives me this:

> Module ''autobind-decorator'' resolves to a non-module entity and cannot be imported using this construct.

Am I doing something wrong?

**Comment by slikts** [comment]
You're not doing anything wrong; the 1.3.4 version published in npm does not include the type definitions. The pull request adding types (#39) was accepted but not published for some reason.

**Comment by stevemao** [comment]
published as 1.4.0. Please try again :)

**Comment by rfgamaral** [comment]
@stevemao Sorry for the delay but I can confirm this now works at method level, not class level as mentioned on #86.

**Comment by stevemao** [comment]
@rfgamaral PR welcome to fix this

**Comment by rfgamaral** [comment]
I was just reporting my findings, I actually prefer to use this per method.
