### ISSUE TITLE
Make it work without requiring Reflect polyfill

### ISSUE THREAD

**Issue by okcoker** [andreypopp/autobind-decorator#5]
Trying to autobind a whole class throws an error for me that complains about [`Reflect`](https://github.com/andreypopp/autobind-decorator/blob/4544e93e7f51bbe5174e5f1539c6c26896f119be/src/index.js#L28) being undefined. 

Just documenting this issue as mentioned [here](https://twitter.com/dan_abramov/status/596082035585855489).

**Comment by andreypopp** [comment]
See https://github.com/andreypopp/autobind-decorator/pull/6#issuecomment-131946020
