### ISSUE TITLE
1.4.1? export = autobind breaks our builds

### ISSUE THREAD

**Issue by dennisfleischmann** [andreypopp/autobind-decorator#51]
Please have a look as fast as possible. We have downgraded to 1.4.0

============================================
Showing  1 changed file  with 1 addition and 1 deletion.
View  
2  index.d.ts
@@ -1,4 +1,4 @@
  declare module 'autobind-decorator' {
    const autobind: ClassDecorator & MethodDecorator;
 -  export default autobind;
 +  export = autobind;
  }
============================================

**Comment by stevemao** [comment]
I don't use typescript. PR welcome

**Comment by ArtemZag** [comment]
@stevemao, but you have index.d.ts file.

**Comment by stevemao** [comment]
@ArtemZag PR welcome
