### ISSUE TITLE
Not working well with react-native 0.53.3

### ISSUE THREAD

**Issue by mieszko4** [andreypopp/autobind-decorator#62]
I use `@autobind` for methods in `class`.

Autobind works well for the first time the component is mounted.
But the second time it is mounted it seems to be bound to the old instance of `this`.

When I remove `@autobind` and use usual `constructor` bind statements all is working as expected.

Has anyone experienced a similar issue? Any suggestions?

**Comment by stevemao** [comment]
does https://github.com/andreypopp/autobind-decorator/pull/57 work for you?

**Comment by mieszko4** [comment]
Oh, sorry, I did not notice that pr before.
Yes, after applying the fix from this pr it works great for me!

**Comment by mieszko4** [comment]
@stevemao Do you think you can merge #57 ?

**Comment by stevemao** [comment]
@mieszko4 could you create a unit test against it?

**Comment by stevemao** [comment]
Let's move the convo there

**Comment by tezqa** [comment]
Why is this issue closed? The PR is not merged.

**Comment by stevemao** [comment]
@tezqa 
> Let's move the convo there

**Comment by tezqa** [comment]
@stevemao sorry I missed it!
