### ISSUE TITLE
Property descriptor is undefined into boundMethod method(used inheritance)

### ISSUE THREAD

**Issue by derkachdeveloper** [andreypopp/autobind-decorator#64]
![image](https://user-images.githubusercontent.com/6834477/41318437-fb34b8aa-6ea0-11e8-8e81-3c3c40187dc5.png)
![image](https://user-images.githubusercontent.com/6834477/41318447-01c8071c-6ea1-11e8-9a71-3c2367626621.png)
![image](https://user-images.githubusercontent.com/6834477/41318456-08e22e10-6ea1-11e8-9ec1-05a5de6ebf48.png)

**Comment by IIIristraM** [comment]
Is any progress in this issue ?

**Comment by stevemao** [comment]
Can you provide the steps of how to replicate this? Actually, if you could submit a PR with failing unit test it would make me understand the problem a lot faster...

**Comment by IIIristraM** [comment]
I use TypeScript v2.8.4

The problem appears in the following example 

```ts
class A {
     @autobind
     protected static method() {}
}

class B extends A {
    @autobind
    protected static method() {}
}
```

typescript has `__decorate` (tslib.es6.js) helper with the following code
```js
function __decorate(decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
}
```

when `__decorate` applied to `B.method` the result of `Object.getOwnPropertyDescriptor(target, key)` is `undefined` which leads to an error in

```js
function boundMethod(target, key, descriptor) {
  var fn = descriptor.value;
```

where `descriptor` is `undefined`

As far as I understand, it happens because of lazy initialization of `autobind`. If I set breakpoint at the beginning of `__decorate` and invoke `target[key]` in browser's console, `Object.getOwnPropertyDescriptor(target, key)` returns descriptor as expected

**Comment by stevemao** [comment]
Any updates on this? Please send a failing unit test to illustrate the problem.

**Comment by bennypowers** [comment]
I have this with 

.babelrc
```json
{
  "presets": [ "@babel/preset-env" ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/proposal-class-properties",
    ["@babel/plugin-proposal-decorators", {
      "decoratorsBeforeExport": true
    }]
  ]
}
```

app.js
```js
import { boundMethod } from 'autobind-decorator';
class LibraryShell extends LitElement {
  @boundMethod
  onRoute(route, params, query) {
    console.log(route, params, query);
    this.route = route;
    this.params = params;
    this.importPage(route);
  }
}
```

**Comment by stevemao** [comment]
@bennypowers did you follow https://github.com/andreypopp/autobind-decorator#modern?
