### ISSUE TITLE
v2.2 breaks create-react-app v1

### ISSUE THREAD

**Issue by nmitha** [andreypopp/autobind-decorator#72]
The changes made in v2.2 cause the following error running `npm run build` with a react-scripts 1.1 (aka "Create React App"):

```
Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file:

        ./node_modules/autobind-decorator/src/index.js:7
```

The above issue went away after downgrading autobind-decorator to 2.1.0.

I'm mostly just posting this here as an FYI in case someone else runs into this...

**Comment by vovchik33** [comment]
Also we get a problem with code minimizing through UglifyJSPlugin in Webpack.

**Comment by stevemao** [comment]
https://github.com/andreypopp/autobind-decorator/issues/69#issuecomment-435626439

**Comment by stevemao** [comment]
Please read https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages
