### ISSUE TITLE
Uglify errors in react scripts

### ISSUE THREAD

**Issue by harinair** [andreypopp/autobind-decorator#73]
I am running into an Uglify error that was traced to autobind-decorator@2.2.1

autobind-decorator@2.1.0 works fine. The following is the error:
```
Failed to compile.

Failed to minify the bundle. Error: static/js/main.d366c2d2.js from UglifyJs
Unexpected token: name (fn) [static/js/main.d366c2d2.js:396674,6]
    at compiler.run (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/@pearson-incubator/react-scripts/scripts/build.js:130:23)
    at emitRecords.err (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/webpack/lib/Compiler.js:269:13)
    at Compiler.emitRecords (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at next (/Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/tapable/lib/Tapable.js:220:14)
    at /Users/ugangha/Sandbox/Pearson/Cite/greenville/node_modules/sw-precache-webpack-plugin/lib/index.js:98:18
    at <anonymous>
Read more here: http://bit.ly/2tRViJ9
```

This error is happening in a "let" statement. From what I read I feel Uglify cannot handle ES6 code and create react scripts does not convert all node modules to ES5 before feeding to Uglify. My assumption is some build option is changed from 2.1.0 to 2.2.1 so that the build is provided in ES6 not pure ES5.

**Comment by jharris4** [comment]
I just ran into the exact same issue.

It's definitely a bug related to the contents of the `package.json` now having `modules: src/index.js` as added in this commit:

https://github.com/andreypopp/autobind-decorator/commit/9edeabf87c29d66e6d3d7ebffd715c05be119470#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by jharris4** [comment]
@stevemao could you please remove `modules` from `package.json`?

The code pointed to by `modules` needs to be ES5 code but with ES6 modules (import/export).

The problem here is that src had ES6 code (including `let` etc).

You can read more about it here: https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

**Comment by stevemao** [comment]
How is adding modern JavaScript to “module” is a bug? We still have “main” entry which point to the same old JavaScript so its not a breaking change. On the other hand, you are using a deprecated minifier and wrong webpack config. 

> The code pointed to by modules needs to be ES5 code but with ES6 modules (import/export).

Who says that? Module entry is supposed to point to scripts with Es modules. Tools usually use this entry for tree shaking.

**Comment by stevemao** [comment]
Let is not future JavaScript. It became standard 3 years ago. If I published typescript, stage 3 features/syntax or flow then its a bug and should be transpiled. If you need to support old environment, you can use Babel env to transpile modern JavaScript to old version.

**Comment by jharris4** [comment]
```Who says that? Module entry is supposed to point to scripts with Es modules. Tools usually use this entry for tree shaking.```

Did you read the link I posted? Basically the authors of webpack & rollup ALL say that `modules` should point to ES5 code with ONLY es6 modules. And since they are the ones who added it to package.json and implemented tree shaking they're probably the best authority on the subject.

```On the other hand, you are using a deprecated minifier and wrong webpack config.```

I'm using the latest version of webpack and the latest minifier that it supports. I maintain several projects that use webpack, so I hardly think I'm using a wrong webpack config. It worked fine until the version of autobind-decorator that broke the rules.

```If you need to support old environment, you can use Babel env to transpile modern JavaScript to old version.```

That is not how the spec for modules in package.json modules works. If you don't want to believe that then I guess this package has hit a dead end and people will need to find alternatives if they want to use autobind decorators with modern tools like webpack or rollup.

Have you tried bundling the latest of autobind-decorator with either rollup or webpack? I suggest you try...

**Comment by stevemao** [comment]
> modules should point to ES5 code with ONLY es6 modules.

I don’t necessarily agree. That article was published a long time ago when es6 was new (the future javascript). Some people only want to target modern browsers (with full support of modern JavaScript), are they forced to run es5 code only?

> Have you tried bundling the latest of autobind-decorator with either rollup or webpack? 

I’m using webpack and I even target ie11 because of the business requirements. I always use Babel to transpile node modules from modern to targeted javascript env (this is what create react app is doing).

**Comment by stevemao** [comment]
> I have never seen a single other package that exports raw es6 source via the modules field

I have seen many packages exporting modern javascript via the `main` field. This is also the reason why create-react-app compiles node_modules. 

> In any case, speaking of "modern javascript" the new "class properties" proposal & babel-plugin let you just replace:

That is already mentioned in the README and I think it's a good alternative
https://github.com/andreypopp/autobind-decorator#alternative

**Comment by harinair** [comment]
Related Bug:
https://github.com/react-dnd/react-dnd/issues/1152

**Comment by jharris4** [comment]
@stevemao interesting, can you share some examples of packages that are exporting es6 syntax (other than es6 modules) via the `main` or `modules` field? I’m curious if any of them are intended for use in the browser vs node.

**Comment by stevemao** [comment]
In any case, we only added a `module` entry to the package.json for modern browsers and tree shaking. So it's a new feature. The old `main` entry is still there any the files are not changed. If you want the old behaviour you can still use the `main` entry so this is not a breaking change.

**Comment by jharris4** [comment]
lol, except you can't use minification anymore with webpack without transpiling node modules first.

The right way to fix it is to use separate lib/es outputs like most other libraries do.

Happy to offer pointers if you're open to it. It's just a matter of forking your babel config to change the modules parameter to either preset-es2015 or preset-env...

A good example is here: https://github.com/react-bootstrap/react-bootstrap/blob/master/.babelrc.js

**Comment by stevemao** [comment]
@jharris4 They use jsx in the src so they have to compile it. For those who want to use modern javascript and only target modern browsers/env what's your recommendation?

**Comment by stevemao** [comment]
> The default create-react-app / react scripts does not support this code.

It does. I'm using create-react-app too.

I think we can add a note on README.

**Comment by stevemao** [comment]
I have added a note just now on readme. let me know if it makes sense

**Comment by jharris4** [comment]
ya, I wasted a couple of hours tracking this down myself.

Definitely should have been a version bump as this is definitely a breaking change.

As a workaround, I've just switched to class properties like I posted earlier. so I'm not using this package anymore...

@stevemao I don't have a good answer for how to allow npm packages to be consumed in es6+ only mode. As far as I know nobody has really solved this problem yet, but maybe a new `next` field in package json to complement the existing `main` and `module` fields would be the way to go. I've already weighed in on how `module` is NOT the place for es6 only code, so not much else I can add despite the fact that I understand your motivation here...

**Comment by stevemao** [comment]
> Definitely should have been a version bump as this is definitely a breaking change.

If we pointed `main` to a ES6 script then it would have been a breaking change.

Thanks @jharris4 . I personally periodically improve my build script and look up create-react-app as a good reference. They have removed deprecated uglify-js and they also compile node_modules (but only from standard javascript).

**Comment by stevemao** [comment]
Please read https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

**Comment by shouvik44** [comment]
> Related Bug:
> [react-dnd/react-dnd#1152](https://github.com/react-dnd/react-dnd/issues/1152)

I couldn't build my app built on Create-React-App using React DnD. Thanks @harinair for pointing to the related thread. If others are experiencing this, the workaround with react dnd is to pin autobind-decorator to version 2.1.0. Since then, I'm able to build just fine.

**Comment by stevemao** [comment]
@shouvik44 did you read the blog I linked?

**Comment by shouvik44** [comment]
@stevemao I read through it, but I didn't understand how to take action. I can't stop using react-DnD, and the older version of autobind-decorator works well for my current needs.

**Comment by catamphetamine** [comment]
> I don’t necessarily agree. That article was published a long time ago when es6 was new (the future javascript). Some people only want to target modern browsers (with full support of modern JavaScript), are they forced to run es5 code only?

LOL.
Most of the people only want their apps to just work and not break suddenly.
Are you forcing those people to hack around your preference of putting incompatible js syntax in the release just because you like it more?
The `module` entry is clearly for ES5 syntax with only ES6 modules, as @jharris4 already said.

**Comment by catamphetamine** [comment]
@stevemao 
> I have seen many packages exporting modern javascript via the main field. This is also the reason why create-react-app compiles node_modules.

And that means that they do it wrong.
If someone jumps from a bridge will you jump too?
I guess you do...

**Comment by catamphetamine** [comment]
@stevemao 
> In any case, we only added a module entry to the package.json for modern browsers and tree shaking. So it's a new feature. The old main entry is still there any the files are not changed. If you want the old file you can still use the main entry so this is not a breaking change.

Man, you don't get it: bundlers do always prefer the `module` entry ignoring `main`.
So you're consciously and willingly breaking everyone's projects because you know Webpack won't compile them and you're fine with that.
Well, no wonder `react-dnd` moved away from this package.

**Comment by stevemao** [comment]
@catamphetamine If I have to argue with you I'll repeat what I have said. Your arguments haven't been constructive and convincing but rather mocking and attempting to taunt me. I suggest be patient and read the babel blog again rather than believing in what you think is right. Coz it's not.

**Comment by stevemao** [comment]
@catamphetamine If you want to learn how to discuss with people properly in a constructive way, have a look at https://github.com/andreypopp/autobind-decorator/issues/78 by @lroling8350. That issue so far has provided really good value. And I really appreciate everyone's inputs. Peace.
