### ISSUE TITLE
v2.2.1 contains es code in npm package (did not compile?)

### ISSUE THREAD

**Issue by pmq20** [andreypopp/autobind-decorator#74]
This makes webpack panic because it saw ES in the source code of autobind-decorator v2.2.1.

![image](https://user-images.githubusercontent.com/13315/48321947-07635780-e660-11e8-8c2a-2135cfb4ded6.png)

![image](https://user-images.githubusercontent.com/13315/48321967-1e09ae80-e660-11e8-88f4-9e733d203c91.png)

**Comment by pmq20** [comment]
autobind-decorator <= 2.1.0 doesn't have this problem because the `let` was `var`

**Comment by stevemao** [comment]
#69 #73

**Comment by stevemao** [comment]
Please read https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages
