### ISSUE TITLE
module tag in package.json is pointing to src not lib

### ISSUE THREAD

**Issue by felipenvaz** [andreypopp/autobind-decorator#75]
On this commit: `https://github.com/andreypopp/autobind-decorator/commit/9edeabf87c29d66e6d3d7ebffd715c05be119470#diff-b9cfc7f2cdf78a7f4b91a753d10865a2` the module tag was added pointing to src/index.js.

Usually, people assume the code in modules is already transpiled to be at least IE11 compliant, but src/index isn't. Only lib/index.js is.

Also, that tag was added without any change in the module version.

Thanks

**Comment by stevemao** [comment]
see `Note uglify users:` in readme

**Comment by stevemao** [comment]
Please read https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages
