### ISSUE TITLE
Failed to minify the code from /autobind-decorator/src/index.js:7

### ISSUE THREAD

**Issue by nguyendviet** [andreypopp/autobind-decorator#77]
I have an error when run`yarn build`. I've tried what @khelkun suggested [here](https://github.com/facebook/create-react-app/issues/5726) but it doesn't work for me. I've also tried to edit `autobind-decorator` to `2.1.1` but it also doesn't work.

This issue was described [here](https://github.com/andreypopp/autobind-decorator/issues/69) but the ticket is closed without a solution so I create this ticket.

```
$ yarn build
yarn run v1.12.3
$ node scripts/build.js

> myapp@0.1.0 build /path/myapp/client
> react-scripts build

Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

    ./node_modules/autobind-decorator/src/index.js:7 

Read more here: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myapp@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /path/.npm/_logs/2018-11-15T22_23_20_735Z-debug.log
✨  Done in 11.02s.
```
Here's my `package.json`:

```
"scripts": {
    "server": "node server.js",
    "client": "node scripts/start-client.js",
    "start": "concurrently \"nodemon server.js\" \"npm run client\"",
    "build": "node scripts/build.js"
  },
```
My build.js and start-client.js inside ./scripts:

```
// build.js
const args = ["run build"];
const opts = { stdio: "inherit", cwd: "client", shell: true };
require("child_process").spawn("npm", args, opts);

// start-client.js
const args = ["start"];
const opts = { stdio: "inherit", cwd: "client", shell: true };
require("child_process").spawn("npm", args, opts);
```

**Comment by stevemao** [comment]
https://github.com/andreypopp/autobind-decorator#note-uglify-users

**Comment by quarryman** [comment]
This link doesnt exist anymore.

**Comment by stevemao** [comment]
@quarryman https://github.com/andreypopp/autobind-decorator#supported-platforms

**Comment by quarryman** [comment]
@khelkun Tnx for your reply.
2.4.0 fixes the issue as it doesnt export es6 in 'module' anymore.
Just to admin, for people using react-create-app it might be not easy to get additional transpiling just to fix this issue as author suggests.
