### ISSUE TITLE
Not Compatible Under IE 11

### ISSUE THREAD

**Issue by JackieLs** [andreypopp/autobind-decorator#83]
Because of the Template Spring \`@boundMethod decorator can only be applied to methods not: ${typeof r}\`
Hope for update.

**Comment by stevemao** [comment]
[We don't support IE10-](https://github.com/andreypopp/autobind-decorator#output)

**Comment by JackieLs** [comment]
> [We don't support IE10-](https://github.com/andreypopp/autobind-decorator#output)

Sorry, I mean IE 11. The Template Strings feature is not compatible under IE 11. [Template strings Browser compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Browser_compatibility)

So if you don't support IE 11, please tell the users, thank you.

**Comment by stevemao** [comment]
Both esm and cjs builds target IE11, so template strings are compiled. I have just installed from npm and don't see any problem with that. Please read https://github.com/andreypopp/autobind-decorator#output

**Comment by stevemao** [comment]
It is compiled to `throw new TypeError("@boundMethod decorator can only be applied to methods not: ".concat(_typeof(fn)));`
